[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor    = "#1E2D55"
backgroundColor = "#F4EFE6"
secondaryBackgroundColor = "#FBF8F1"
textColor       = "#1A1812"
font            = "sans serif"
